#!/usr/bin/env python
import sys
import getopt
import world
import theano as th
import visualize
import scenario

th.config.optimizer_verbose = True
th.config.allow_gc = False

if __name__ == '__main__':
    optlist, args = getopt.gnu_getopt(sys.argv, 'w:m:o:c:s:')
    opts = dict(optlist)
    filename = args[1]
    if '-w' in opts:
        try:
            the_world = getattr(world, opts['-w'])()
        except AttributeError:
            the_world = scenario.env_from(getattr(scenario, (filename.split('/')[-1]).split('-')[0]))
    else:
        try:
            the_world = getattr(world, (filename.split('/')[-1]).split('-')[0])()
        except AttributeError:
            the_world = scenario.env_from(getattr(scenario, (filename.split('/')[-1]).split('-')[0]))
#    the_world = the_world()
    magnify = 1.
    if '-m' in opts:
        magnify = float(opts['-m'])
    vis = visualize.Visualizer(0.2, name='Visualizer', magnify=magnify, fullscreen=False)
    if '-o' in opts:
        vis.camera_center = list(eval(opts['-o']))
    if '-c' in opts:
        colors = opts['-c'].split()
        for i, c in enumerate(colors):
            the_world.cars[i].color = c
    if '-s' in opts:
        output = opts['-s']
        vis.output = output
    vis.use_world(the_world)
    vis.main_car = the_world.cars[-1]
    vis.autoquit = True
    vis.set_heat(the_world.cars[0].reward)
    vis.run(filename)
